### PR TITLE
Escape source path in VSCode protocol output event

### LINKED ISSUE #175: Unescaped source path in JSON body of DAP output event causes errors in nvim-dap
### Description

I'm trying to use netcoredbg from neovim through nvim-dap and I get the following errors when debuging a simple ASP.NET Core Web API template project on Windows: 

```
Error executing vim.schedule lua callback: ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: Expected value but found invalid escape code at character 209
stack traceback:
    [C]: in function 'json_decode'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: in function 'handle_body'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1479: in function 'fn'
    vim/_editor.lua:351: in function <vim/_editor.lua:350>

Error executing vim.schedule lua callback: ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: Expected value but found invalid escape code at character 217
stack traceback:
    [C]: in function 'json_decode'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: in function 'handle_body'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1479: in function 'fn'
    vim/_editor.lua:351: in function <vim/_editor.lua:350>

Error executing vim.schedule lua callback: ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: Expected value but found invalid escape code at character 201
stack traceback:
    [C]: in function 'json_decode'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: in function 'handle_body'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1479: in function 'fn'
    vim/_editor.lua:351: in function <vim/_editor.lua:350>

Error executing vim.schedule lua callback: ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: Expected value but found invalid escape code at character 212
stack traceback:
    [C]: in function 'json_decode'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:983: in function 'handle_body'
    ...ppData/Local/nvim-data/lazy/nvim-dap/lua/dap/session.lua:1479: in function 'fn'
    vim/_editor.lua:351: in function <vim/_editor.lua:350>
```

I added a few traces in nvim-dap's session.lua and found the problematic JSON body:

```
{
  "seq": 111,
  "event": "output",
  "type": "event",
  "body": {
    "category": "stdout",
    "output"...r\n",
    "source": {
      "name": "Program.cs",
      "path": "C:\Dev\csharp-project\WebApi1\Program.cs"
    }
  }
}
````

Note the unescaped backslashes in the path of the source file. Looking at the code of netcoredgb, it seems that it could easily be fixed by wrapping ```source.path``` in an ```EscapedString<JSON_escape_rules>``` within ```serialize_output``` in src/protocol/vscodeprotocol.cpp.

I have tested this fix on my side and it works, I can submit a PR if needed.

Just for the record, here is my nvim-dap configuration:

```
local dap = require("dap")

dap.adapters["coreclr"] = {
  type = "executable",
  command = vim.fn.exepath("netcoredbg"),
   args = { "--interpreter=vscode" },
   options = {
     detached = false,
   },
}

dap.configurations["cs"] = {
  {
    type = "coreclr",
    name = "Debug C# App",
    request = "launch",
    program = function()
        return vim.fn.input("Path to dll", vim.fn.getcwd() .. "/bin/Debug/", "file")
    end,
  },
}
````

And I created my C# App using ```dotnet new webapi -o WebApi1```.

### PR DESCRIPTION
**Pull request by tbrauredev**
Fixes #175

Tested on Windows through nvim-dap with a .Net Core Web API template project, test suite is also still passing on Windows.

### CODE REVIEW

**Comment by viewizard** [comment]
Thanks! Looks good to me. I moved this PR into internal dev repo, all CI tests are passed. Will be merged into internal dev repo and will appear in public repo after next repo sync.

**Review by 9poole — APPROVED** [review]

**Comment by dkattan** [comment]
I'd love to see this get merged in as well. I'm getting a ton of these errors

**Review by gbalykov — APPROVED** [review]
Thanks for your contribution! This change is already merged in internal dev repo, will be available in upstream on next repo sync.

**Comment by dkattan** [comment]
> Thanks for your contribution! This change is already merged in internal dev repo, will be available in upstream on next repo sync.

Any idea when that will be?

**Comment by dkattan** [comment]
> > Any idea when that will be?
> 
> Next release will be in October and will include fixes for other issues too.

Just want to say I appreciate that this project exists. Despite this issue it works great for Debugging C# in Cursor AI

**Comment by gbalykov** [comment]
Thanks for your contribution, this is part of latest release

**Comment by dkattan** [comment]
I updated to the latest release yesterday and it is working great!

**Pull request closed without merging**
