### PR TITLE
Adding limits due to GCC11 changes

### PR DESCRIPTION
**Pull request by passeride**
Could not build with GCC11, found issue and added limit header

https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-changes

### CODE REVIEW

**Comment by alpencolt** [comment]
Like dotnet runtime project we use clang for ncdb build and never tested with gcc. Have you build with gcc before?

More correct way to fix your scenario is using `limits.h` from our project:
```
#include "utils/limits.h"
```
Which makes correct system header including for different compiler versions and OSes.
Could you check GCC11 build with such change?

**Comment by passeride** [comment]
When using that include statement it fails

**Comment by viewizard** [comment]
@passeride thanks for your PR, I will move it into our internal github (will be in public repo at next sync).

**Comment by viewizard** [comment]
In upstream now:
https://github.com/Samsung/netcoredbg/commit/cd606fad353894908bfee183f695c72a264ef939

**Pull request closed without merging**
